In [1]:
import pandas as pd

## The 20 newsgroups dataset

The [20 Newsgroups data set](http://qwone.com/~jason/20Newsgroups/) is a collection of approximately 20,000 newsgroup documents, partitioned (nearly) evenly across 20 different newsgroups.
The 20 newsgroups collection has become a popular data set for experiments in text applications of machine learning techniques, such as text classification and text clustering.

The data is organized into 20 different newsgroups, each corresponding to a different topic:

- 'atheism',
- 'comp.graphics',
- 'comp.os.ms-windows.misc',
- 'comp.sys.ibm.pc.hardware',
- 'comp.sys.mac.hardware',
- 'comp.windows.x',
- 'misc.forsale',
- 'rec.autos',
- 'rec.motorcycles',
- 'rec.sport.baseball',
- 'rec.sport.hockey',
- 'sci.crypt',
- 'sci.electronics',
- 'sci.med',
- 'sci.space',
- 'soc.religion.christian',
- 'talk.politics.guns',
- 'talk.politics.mideast',
- 'talk.politics.misc',
- 'talk.religion.misc']

 we will work on a partial dataset with only 6 categories out of the 20 available in the dataset

In [2]:
from sklearn.datasets import fetch_20newsgroups

In [3]:
# choose, for example, 6 categories
categories = [
    'alt.atheism',
    'comp.windows.x',
    'rec.autos',
    'rec.sport.baseball',
    'sci.electronics',
    'sci.space',
]

train = fetch_20newsgroups(subset='train', 
                                categories=categories,
                                remove=('headers', 'footers', 'quotes')
                          )

test = fetch_20newsgroups(subset='test', 
                                categories=categories,
                                remove=('headers', 'footers', 'quotes')
                          )

In [4]:
train_data = pd.DataFrame({'text' : train['data'], 
                           'category' : train['target']})
train_data.head()

                                                text  category
0  Benedikt Rosenau writes, with great authority:...         0
1  \nI don't understand this last statement about...         2
2  I'd like to compile X11r5 on a Sony NWS-1750 r...         1
3  \n\n\nHow do you know it's based on ignorance,...         0
4  \nmuch crap deleted\n\n\nDEAD WRONG!  Last tim...         3

In [5]:
test_data = pd.DataFrame({'text' : test['data'], 
                           'category' : test['target']})
test_data.head()

                                                text  category
0  I can see it now emblazened across the evening...         5
1  The color of the board shows the composition o...         4
2  Regarding the feasability of retrieving the HS...         5
3  \nI believe Acker got a ring from his wife whe...         3
4  \n\nThe new Cruisers DO NOT have independent s...         2

In [6]:
train['target_names']

['alt.atheism',
 'comp.windows.x',
 'rec.autos',
 'rec.sport.baseball',
 'sci.electronics',
 'sci.space']

In [7]:
# topics
train_data.category.value_counts()

category
3    597
2    594
1    593
5    593
4    591
0    480
Name: count, dtype: int64

In [8]:
# topics
test_data.category.value_counts()

category
3    397
2    396
1    395
5    394
4    393
0    319
Name: count, dtype: int64

In [9]:
# space
print(train_data[train_data.category==5].sample().iloc[0,0])

In pure speculation, I would guess cautions based on hazardous
pre-launch ops would qualify.  Something like "Caution:  SRBs
have just been armed."

**Goal**:  classify documents from the dataset by their topic

## Training a classification model

In [10]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import GridSearchCV

In [11]:
X_train = train_data.text
y_train = train_data.category

In [12]:
pipe = Pipeline(steps=[
    ('vect', TfidfVectorizer(sto_words='english')), 
    ('clf', LogisticRegression()) 
])
pipe

Pipeline(steps=[('vect', TfidfVectorizer()), ('clf', LogisticRegression())])

In [16]:
params_dic =  {'vect__max_features' : [5000,7000,10000],
               #'vect__stop_words' : ['english', None],
               'vect__min_df' : [5,10],
               "vect__max_df": [0.9, 0.95],
               'vect__ngram_range' : [(1,1), (1,2)],
               'vect__use_idf' : [True,False]}

In [17]:
grid = GridSearchCV(pipe,
                    params_dic,
                    scoring='accuracy',
                    cv=5, n_jobs=-1, 
                    verbose=True)
grid.fit(X_train,y_train)

Fitting 5 folds for each of 48 candidates, totalling 240 fits

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('vect', TfidfVectorizer()),
                                       ('clf', LogisticRegression())]),
             n_jobs=-1,
             param_grid={'vect__max_df': [0.9, 0.95],
                         'vect__max_features': [5000, 7000, 10000],
                         'vect__min_df': [5, 10],
                         'vect__ngram_range': [(1, 1), (1, 2)],
                         'vect__use_idf': [True, False]},
             scoring='accuracy', verbose=True)

In [18]:
grid.best_score_

0.8364279253696809

In [19]:
grid.best_params_

{'vect__max_df': 0.9,
 'vect__max_features': 7000,
 'vect__min_df': 5,
 'vect__ngram_range': (1, 1),
 'vect__use_idf': True}

In [20]:
best_clf = grid.best_estimator_

In [21]:
# evaluate the model
X_test = test_data.text
y_test = test_data.category
y_test_pred = best_clf.predict(X_test)

In [22]:
confusion_matrix(y_test,y_test_pred)

array([[233,   7,  13,  25,   7,  34],
       [  5, 340,   2,  13,  24,  11],
       [  9,   4, 299,  37,  31,  16],
       [ 22,   3,   6, 351,   7,   8],
       [  9,  15,  25,  18, 304,  22],
       [ 17,   7,  14,  26,  24, 306]], dtype=int64)

In [23]:
train['target_names']

['alt.atheism',
 'comp.windows.x',
 'rec.autos',
 'rec.sport.baseball',
 'sci.electronics',
 'sci.space']

In [24]:
best_clf.predict(['I always wanted to be an astronaut','I hate Windows 10', "I need to clean the window of my spaceship"])

array([5, 1, 1], dtype=int64)

In [25]:
best_clf

Pipeline(steps=[('vect',
                 TfidfVectorizer(max_df=0.9, max_features=7000, min_df=5)),
                ('clf', LogisticRegression())])

In [27]:
import numpy as np

In [54]:
# show to n features 
n = 10
tfidf = best_clf["vect"]
logreg = best_clf["clf"]

feature_names = np.array(tfidf.get_feature_names_out())
coefs = logreg.coef_
target_names = train['target_names']

for i in range(len(target_names)):
    print("=" * 60)
    print(f"Top {n} features for class: {target_names[i]}")
    print("=" * 60)

    # pick the weights for this class
    class_coefs = coefs[i]
    sort_idx = np.argsort(class_coefs)[::-1]
    top_features = feature_names[sort_idx][0:n]
    print(top_features)

============================================================
Top 10 features for class: alt.atheism
============================================================
['god' 'religion' 'that' 'bible' 'atheism' 'of' 'you' 'islam' 'not'
 'islamic']
============================================================
Top 10 features for class: comp.windows.x
============================================================
['window' 'server' 'motif' 'windows' 'widget' 'xterm' 'file' 'x11r5'
 'using' 'mit']
============================================================
Top 10 features for class: rec.autos
============================================================
['car' 'cars' 'my' 'engine' 'oil' 'dealer' 'ford' 'auto' 'gt' 'toyota']
============================================================
Top 10 features for class: rec.sport.baseball
============================================================
['he' 'baseball' 'team' 'game' 'players' 'games' 'year' 'cubs' 'runs'
 'stadium']
============================================================
Top 10 features for class: sci.electronics
============================================================
['circuit' 'electronics' 'power' 'chip' 'tv' 'used' 'ground' 'voltage'
 'chips' 'phone']
============================================================
Top 10 features for class: sci.space
============================================================
['space' 'nasa' 'orbit' 'launch' 'moon' 'earth' 'spacecraft' 'shuttle'
 'of' 'lunar']